### ISSUE TITLE
[TODO] UI Enhancement 

### ISSUE THREAD

**Issue by wenjie1991** [wenjie1991/TSVdb#1]
- [x] CSS for `index.html`. 
- [x] Data loading gif waiting for animation for `plot.html`.
- [x] plot.html is dull ~ try to make it colorful. So CSS.
- [x] Suggestion(apologies) for IE user.
- [x] Adjust picture size.

**Comment by palmerye** [comment]
in feature branch.
- [x]  add new `index.html` instead of.
